// export { fruits } from './words/fruits'
// export { humanRelation } from './words/humanRelation'
// export { numbers } from './words/numbers'
export { bodyMovements } from './words/verbs/bodyMovements'
export { humanAction } from './words/verbs/humanAction'
// export { usefulPhrases } from './phrases/usefulPhrases'
// export { facialExpression } from './words/facialExpression'
// export { greetings } from './phrases/greetings'
