export { fruits } from './words/fruits'
export { humanRelation } from './words/humanRelation'
export { numbers } from './words/numbers'
export { bodyMovements } from './words/bodyMovements'
export { usefulPhrases } from './words/usefulPhrases'
export { facialExpression } from './words/facialExpression'
export { greetings } from './words/greetings'
