import type { FlashCardsType } from './Flashcards.type'

export const fruits: Omit<FlashCardsType, 'id'>[] = [
  {
    word: 'Apple',
    translations: { DE: 'Apfel', CN: '苹果', JP: 'りんご' },
    pinyin: 'Píngguǒ',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Banana',
    translations: { DE: 'Banane', CN: '香蕉', JP: 'バナナ' },
    pinyin: 'Xiāngjiāo',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Orange',
    translations: { DE: 'Orange', CN: '橙子', JP: 'オレンジ' },
    pinyin: 'Chéngzi',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Strawberry',
    translations: { DE: 'Erdbeere', CN: '草莓', JP: 'いちご' },
    pinyin: 'Cǎoméi',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Grape',
    translations: { DE: 'Traube', CN: '葡萄', JP: 'ぶどう' },
    pinyin: 'Pútáo',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Watermelon',
    translations: { DE: 'Wassermelone', CN: '西瓜', JP: 'スイカ' },
    pinyin: 'Xīguā',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Pineapple',
    translations: { DE: 'Ananas', CN: '菠萝', JP: 'パイナップル' },
    pinyin: 'Bōluó',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Mango',
    translations: { DE: 'Mango', CN: '芒果', JP: 'マンゴー' },
    pinyin: 'Mángguǒ',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Peach',
    translations: { DE: 'Pfirsich', CN: '桃子', JP: '桃' },
    pinyin: 'Táozi',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Pear',
    translations: { DE: 'Birne', CN: '梨', JP: '梨' },
    pinyin: 'Lí',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Cherry',
    translations: { DE: 'Kirsche', CN: '樱桃', JP: 'さくらんぼ' },
    pinyin: 'Yīngtáo',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Lemon',
    translations: { DE: 'Zitrone', CN: '柠檬', JP: 'レモン' },
    pinyin: 'Níngméng',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Lime',
    translations: { DE: 'Limette', CN: '青柠', JP: 'ライム' },
    pinyin: 'Qīngníng',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Kiwi',
    translations: { DE: 'Kiwi', CN: '猕猴桃', JP: 'キウイ' },
    pinyin: 'Míhóutáo',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Papaya',
    translations: { DE: 'Papaya', CN: '木瓜', JP: 'パパイヤ' },
    pinyin: 'Mùguā',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Coconut',
    translations: { DE: 'Kokosnuss', CN: '椰子', JP: 'ココナッツ' },
    pinyin: 'Yēzi',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Blueberry',
    translations: { DE: 'Heidelbeere', CN: '蓝莓', JP: 'ブルーベリー' },
    pinyin: 'Lánméi',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Raspberry',
    translations: { DE: 'Himbeere', CN: '覆盆子', JP: 'ラズベリー' },
    pinyin: 'Fùpénzi',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Blackberry',
    translations: { DE: 'Brombeere', CN: '黑莓', JP: 'ブラックベリー' },
    pinyin: 'Hēiméi',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Pomegranate',
    translations: { DE: 'Granatapfel', CN: '石榴', JP: 'ザクロ' },
    pinyin: 'Shíliu',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Fig',
    translations: { DE: 'Feige', CN: '无花果', JP: 'イチジク' },
    pinyin: 'Wúhuāguǒ',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Plum',
    translations: { DE: 'Pflaume', CN: '李子', JP: 'プラム' },
    pinyin: 'Lǐzi',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Apricot',
    translations: { DE: 'Aprikose', CN: '杏子', JP: 'アンズ' },
    pinyin: 'Xìngzi',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Melon',
    translations: { DE: 'Melone', CN: '甜瓜', JP: 'メロン' },
    pinyin: 'Tiánguā',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Cantaloupe',
    translations: { DE: 'Cantaloupe-Melone', CN: '哈密瓜', JP: 'カンタロープ' },
    pinyin: 'Hāmìguā',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Grapefruit',
    translations: { DE: 'Grapefruit', CN: '葡萄柚', JP: 'グレープフルーツ' },
    pinyin: 'Pútáoyòu',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Guava',
    translations: { DE: 'Guave', CN: '番石榴', JP: 'グアバ' },
    pinyin: 'Fānshíliu',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Lychee',
    translations: { DE: 'Litschi', CN: '荔枝', JP: 'ライチ' },
    pinyin: 'Lìzhī',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Persimmon',
    translations: { DE: 'Kaki', CN: '柿子', JP: '柿' },
    pinyin: 'Shìzi',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Dragon fruit',
    translations: { DE: 'Drachenfrucht', CN: '火龙果', JP: 'ドラゴンフルーツ' },
    pinyin: 'Huǒlóngguǒ',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Passion fruit',
    translations: {
      DE: 'Passionsfrucht',
      CN: '百香果',
      JP: 'パッションフルーツ',
    },
    pinyin: 'Bǎixiāngguǒ',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Cranberry',
    translations: { DE: 'Preiselbeere', CN: '蔓越莓', JP: 'クランベリー' },
    pinyin: 'Mànyuèméi',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Nectarine',
    translations: { DE: 'Nektarine', CN: '油桃', JP: 'ネクタリン' },
    pinyin: 'Yóutáo',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Avocado',
    translations: { DE: 'Avocado', CN: '牛油果', JP: 'アボカド' },
    pinyin: 'Niúyóuguǒ',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Tangerine',
    translations: { DE: 'Mandarine', CN: '橘子', JP: 'みかん' },
    pinyin: 'Júzi',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Date',
    translations: { DE: 'Dattel', CN: '枣', JP: 'ナツメヤシ' },
    pinyin: 'Zǎo',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Currant',
    translations: { DE: 'Johannisbeere', CN: '醋栗', JP: 'フサスグリ' },
    pinyin: 'Cùlì',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Mulberry',
    translations: { DE: 'Maulbeere', CN: '桑葚', JP: '桑の実' },
    pinyin: 'Sāngshèn',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Starfruit',
    translations: { DE: 'Sternfrucht', CN: '杨桃', JP: 'スターフルーツ' },
    pinyin: 'Yángtáo',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Durian',
    translations: { DE: 'Durian', CN: '榴莲', JP: 'ドリアン' },
    pinyin: 'Liúlián',
    tag: '',
    masteryLevel: 1,
  },
]
