import { slugify } from '@/utils/slugify'
import type { FlashCardsType } from './Flashcards.type'

export const humanRelation: Omit<FlashCardsType, 'id'>[] = [
  {
    word: 'Mother',
    translations: { DE: 'Mutter', CN: '妈妈', JP: 'お母さん' },
    pinyin: 'Māma',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Father',
    translations: { DE: 'Vater', CN: '爸爸', JP: 'お父さん' },
    pinyin: 'Bàba',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Sister',
    translations: { DE: 'Schwester', CN: '姐妹', JP: '姉妹' },
    pinyin: 'Jiěmèi',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Brother',
    translations: { DE: 'Bruder', CN: '兄弟', JP: '兄弟' },
    pinyin: 'Xiōngdì',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Friend',
    translations: { DE: 'Freund', CN: '朋友', JP: '友達' },
    pinyin: 'Péngyǒu',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Grandmother',
    translations: { DE: 'Großmutter', CN: '奶奶', JP: 'おばあさん' },
    pinyin: 'Nǎinai',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Grandfather',
    translations: { DE: 'Großvater', CN: '爷爷', JP: 'おじいさん' },
    pinyin: 'Yéye',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Uncle',
    translations: { DE: 'Onkel', CN: '叔叔', JP: 'おじさん' },
    pinyin: 'Shūshu',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Aunt',
    translations: { DE: 'Tante', CN: '阿姨', JP: 'おばさん' },
    pinyin: 'Āyí',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Cousin',
    translations: { DE: 'Cousin/Cousine', CN: '表亲', JP: 'いとこ' },
    pinyin: 'Biǎoqīn',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Nephew',
    translations: { DE: 'Neffe', CN: '侄子', JP: '甥' },
    pinyin: 'Zhízi',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Niece',
    translations: { DE: 'Nichte', CN: '侄女', JP: '姪' },
    pinyin: 'Zhínǚ',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Husband',
    translations: { DE: 'Ehemann', CN: '丈夫', JP: '夫' },
    pinyin: 'Zhàngfu',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Wife',
    translations: { DE: 'Ehefrau', CN: '妻子', JP: '妻' },
    pinyin: 'Qīzi',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Son',
    translations: { DE: 'Sohn', CN: '儿子', JP: '息子' },
    pinyin: 'Érzi',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Daughter',
    translations: { DE: 'Tochter', CN: '女儿', JP: '娘' },
    pinyin: "Nǚ'ér",
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Parent',
    translations: { DE: 'Elternteil', CN: '父母', JP: '親' },
    pinyin: 'Fùmǔ',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Child',
    translations: { DE: 'Kind', CN: '孩子', JP: '子供' },
    pinyin: 'Háizi',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Twin',
    translations: { DE: 'Zwilling', CN: '双胞胎', JP: '双子' },
    pinyin: 'Shuāngbāotāi',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Stepmother',
    translations: { DE: 'Stiefmutter', CN: '继母', JP: '継母' },
    pinyin: 'Jìmǔ',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Stepfather',
    translations: { DE: 'Stiefvater', CN: '继父', JP: '継父' },
    pinyin: 'Jìfù',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Stepsister',
    translations: { DE: 'Stiefschwester', CN: '继姐妹', JP: '継姉妹' },
    pinyin: 'Jì jiěmèi',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Stepbrother',
    translations: { DE: 'Stiefbruder', CN: '继兄弟', JP: '継兄弟' },
    pinyin: 'Jì xiōngdì',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Mother-in-law',
    translations: { DE: 'Schwiegermutter', CN: '婆婆', JP: '姑' },
    pinyin: 'Pópo',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Father-in-law',
    translations: { DE: 'Schwiegervater', CN: '公公', JP: '舅' },
    pinyin: 'Gōnggong',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Sister-in-law',
    translations: { DE: 'Schwägerin', CN: '嫂子', JP: '義理の姉妹' },
    pinyin: 'Sǎozi',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Brother-in-law',
    translations: { DE: 'Schwager', CN: '姐夫', JP: '義理の兄弟' },
    pinyin: 'Jiěfu',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Son-in-law',
    translations: { DE: 'Schwiegersohn', CN: '女婿', JP: '婿' },
    pinyin: 'Nǚxù',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Daughter-in-law',
    translations: { DE: 'Schwiegertochter', CN: '儿媳', JP: '嫁' },
    pinyin: 'Érxí',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Fiancé',
    translations: { DE: 'Verlobter', CN: '未婚夫', JP: '婚約者' },
    pinyin: 'Wèihūnfū',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Fiancée',
    translations: { DE: 'Verlobte', CN: '未婚妻', JP: '婚約者' },
    pinyin: 'Wèihūnqī',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Boyfriend',
    translations: { DE: 'Freund', CN: '男朋友', JP: '彼氏' },
    pinyin: 'Nán péngyǒu',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Girlfriend',
    translations: { DE: 'Freundin', CN: '女朋友', JP: '彼女' },
    pinyin: 'Nǚ péngyǒu',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Neighbor',
    translations: { DE: 'Nachbar', CN: '邻居', JP: '隣人' },
    pinyin: 'Línjū',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Colleague',
    translations: { DE: 'Kollege', CN: '同事', JP: '同僚' },
    pinyin: 'Tóngshì',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Classmate',
    translations: { DE: 'Klassenkamerad', CN: '同学', JP: 'クラスメート' },
    pinyin: 'Tóngxué',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Mentor',
    translations: { DE: 'Mentor', CN: '导师', JP: 'メンター' },
    pinyin: 'Dǎoshī',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Roommate',
    translations: { DE: 'Mitbewohner', CN: '室友', JP: 'ルームメート' },
    pinyin: 'Shìyǒu',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Acquaintance',
    translations: { DE: 'Bekannter', CN: '熟人', JP: '知人' },
    pinyin: 'Shúrén',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Partner',
    translations: { DE: 'Partner', CN: '伴侣', JP: 'パートナー' },
    pinyin: 'Bànlǚ',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Widow',
    translations: { DE: 'Witwe', CN: '寡妇', JP: '未亡人' },
    pinyin: 'Guǎfù',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Widower',
    translations: { DE: 'Witwer', CN: '鳏夫', JP: 'やもめ' },
    pinyin: 'Guānfū',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Godmother',
    translations: { DE: 'Patin', CN: '教母', JP: '名付け親' },
    pinyin: 'Jiàomǔ',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Godfather',
    translations: { DE: 'Pate', CN: '教父', JP: '名付け親' },
    pinyin: 'Jiàofù',
    tag: '',
    masteryLevel: 1,
  },
  {
    word: 'Best friend',
    translations: { DE: 'bester Freund', CN: '最好的朋友', JP: '親友' },
    pinyin: 'Zuì hǎo de péngyǒu',
    tag: '',
    masteryLevel: 1,
  },
]

export const cardsHumanRelation: FlashCardsType[] = humanRelation.map(
  (card, i) => ({
    ...card,
    id: slugify(card.word) + i,
  })
)
