import type { FlashCardsType } from '../../Flashcards.type'

export const numbers: FlashCardsType = {
  name: 'numbers',
  id: 'numbers',
  cards: [
    {
      word: 'one',
      translations: { DE: 'eins', CN: '一', JP: '一 (ichi)', UA: 'один' },
      pronunciation: { CN: 'yī', UA: 'odyn' },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'two',
      translations: { DE: 'zwei', CN: '二', JP: '二 (ni)', UA: 'два' },
      pronunciation: { CN: 'èr', UA: 'dva' },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'three',
      translations: { DE: 'drei', CN: '三', JP: '三 (san)', UA: 'три' },
      pronunciation: { CN: 'sān', UA: 'try' },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'four',
      translations: { DE: 'vier', CN: '四', JP: '四 (yon)', UA: 'чотири' },
      pronunciation: { CN: 'sì', UA: 'chotyry' },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'five',
      translations: { DE: 'fünf', CN: '五', JP: '五 (go)', UA: "п'ять" },
      pronunciation: { CN: 'wǔ', UA: "pyat'" },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'six',
      translations: { DE: 'sechs', CN: '六', JP: '六 (roku)', UA: 'шість' },
      pronunciation: { CN: 'liù', UA: "shist'" },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'seven',
      translations: { DE: 'sieben', CN: '七', JP: '七 (nana)', UA: 'сім' },
      pronunciation: { CN: 'qī', UA: 'sim' },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'eight',
      translations: { DE: 'acht', CN: '八', JP: '八 (hachi)', UA: 'вісім' },
      pronunciation: { CN: 'bā', UA: 'visim' },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'nine',
      translations: { DE: 'neun', CN: '九', JP: '九 (kyū)', UA: "дев'ять" },
      pronunciation: { CN: 'jiǔ', UA: "dev'yat'" },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'ten',
      translations: { DE: 'zehn', CN: '十', JP: '十 (jū)', UA: 'десять' },
      pronunciation: { CN: 'shí', UA: "desyat'" },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'eleven',
      translations: {
        DE: 'elf',
        CN: '十一',
        JP: '十一 (jūichi)',
        UA: 'одинадцять',
      },
      pronunciation: { CN: 'shíyī', UA: "odynadtsyat'" },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'twelve',
      translations: {
        DE: 'zwölf',
        CN: '十二',
        JP: '十二 (jūni)',
        UA: 'дванадцять',
      },
      pronunciation: { CN: "shí'èr", UA: "dvanadtsyat'" },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'thirteen',
      translations: {
        DE: 'dreizehn',
        CN: '十三',
        JP: '十三 (jūsan)',
        UA: 'тринадцять',
      },
      pronunciation: { CN: 'shísān', UA: "trynadtsyat'" },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'fourteen',
      translations: {
        DE: 'vierzehn',
        CN: '十四',
        JP: '十四 (jūyon)',
        UA: 'чотирнадцять',
      },
      pronunciation: { CN: 'shísì', UA: "chotyrnadtsyat'" },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'fifteen',
      translations: {
        DE: 'fünfzehn',
        CN: '十五',
        JP: '十五 (jūgo)',
        UA: "п'ятнадцять",
      },
      pronunciation: { CN: 'shíwǔ', UA: "pyatnadtsyat'" },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'sixteen',
      translations: {
        DE: 'sechzehn',
        CN: '十六',
        JP: '十六 (jūroku)',
        UA: 'шістнадцять',
      },
      pronunciation: { CN: 'shíliù', UA: "shistnadtsyat'" },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'seventeen',
      translations: {
        DE: 'siebzehn',
        CN: '十七',
        JP: '十七 (jūnana)',
        UA: 'сімнадцять',
      },
      pronunciation: { CN: 'shíqī', UA: "simnadtsyat'" },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'eighteen',
      translations: {
        DE: 'achtzehn',
        CN: '十八',
        JP: '十八 (jūhachi)',
        UA: 'вісімнадцять',
      },
      pronunciation: { CN: 'shíbā', UA: "visimnadtsyat'" },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'nineteen',
      translations: {
        DE: 'neunzehn',
        CN: '十九',
        JP: '十九 (jūkyū)',
        UA: "дев'ятнадцять",
      },
      pronunciation: { CN: 'shíjiǔ', UA: "dev'yatnadtsyat'" },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'twenty',
      translations: {
        DE: 'zwanzig',
        CN: '二十',
        JP: '二十 (nijū)',
        UA: 'двадцять',
      },
      pronunciation: { CN: 'èrshí', UA: "dvadtsyat'" },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'thirty',
      translations: {
        DE: 'dreißig',
        CN: '三十',
        JP: '三十 (sanjū)',
        UA: 'тридцять',
      },
      pronunciation: { CN: 'sānshí', UA: "trydtsyat'" },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'forty',
      translations: {
        DE: 'vierzig',
        CN: '四十',
        JP: '四十 (yonjū)',
        UA: 'сорок',
      },
      pronunciation: { CN: 'sìshí', UA: 'sorok' },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'fifty',
      translations: {
        DE: 'fünfzig',
        CN: '五十',
        JP: '五十 (gojū)',
        UA: "п'ятдесят",
      },
      pronunciation: { CN: 'wǔshí', UA: "p'yatdesyat" },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'sixty',
      translations: {
        DE: 'sechzig',
        CN: '六十',
        JP: '六十 (rokujū)',
        UA: 'шістдесят',
      },
      pronunciation: { CN: 'liùshí', UA: 'shistdesyat' },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'seventy',
      translations: {
        DE: 'siebzig',
        CN: '七十',
        JP: '七十 (nanajū)',
        UA: 'сімдесят',
      },
      pronunciation: { CN: 'qīshí', UA: 'simdesyat' },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'eighty',
      translations: {
        DE: 'achtzig',
        CN: '八十',
        JP: '八十 (hachijū)',
        UA: 'вісімдесят',
      },
      pronunciation: { CN: 'bāshí', UA: 'visimdesyat' },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'hundred',
      translations: { DE: 'hundert', CN: '百', JP: '百 (hyaku)', UA: 'сто' },
      pronunciation: { CN: 'bǎi', UA: 'sto' },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'thousand',
      translations: { DE: 'tausend', CN: '千', JP: '千 (sen)', UA: 'тисяча' },
      pronunciation: { CN: 'qiān', UA: 'tysyacha' },
      tag: 'numbers',
      masteryLevel: 1,
    },
    {
      word: 'million',
      translations: {
        DE: 'Million',
        CN: '百万',
        JP: '百万 (hyakuman)',
        UA: 'мільйон',
      },
      pronunciation: { CN: 'bǎiwàn', UA: "mil'yon" },
      tag: '',
      masteryLevel: 1,
    },
    {
      word: 'billion',
      translations: {
        DE: 'Milliarde',
        CN: '十亿',
        JP: '十億 (jūoku)',
        UA: 'мільярд',
      },
      pronunciation: { CN: 'shíyì', UA: "mil'yard" },
      tag: '',
      masteryLevel: 1,
    },
  ],
}
